# Generated by Django 5.0.3 on 2024-04-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=16)),
                ('token', models.TextField()),
                ('random_code', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ' unauthenticated user',
                'verbose_name_plural': ' unauthenticated users',
                'ordering': ('created',),
            },
        ),
    ]
