# Generated by Django 5.0.3 on 2024-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='token',
            field=models.UUIDField(unique=True),
        ),
    ]
