# Generated by Django 5.0.3 on 2024-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_registermodel_token'),
        ('Product', '0039_remove_productmodel_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='Product.productmodel'),
        ),
    ]
