# Generated by Django 5.0.3 on 2024-07-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_favorites'),
        ('Product', '0039_remove_productmodel_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='favorites', to='Product.productmodel'),
        ),
    ]
