# Generated by Django 5.0.3 on 2024-07-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_user_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100, verbose_name='receiver name ')),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
