# Generated by Django 5.0.3 on 2024-08-07 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_usershippingaddress'),
        ('Product', '0056_alter_productmodel_category_alter_productmodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, editable=False, related_name='favorites', to='Product.productmodel'),
        ),
    ]
