# Generated by Django 5.0.3 on 2024-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_usershippingaddress_user_alter_user_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='user/profile')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
