# Generated by Django 5.0.3 on 2024-04-10 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='product name')),
                ('product_description', models.TextField(blank=True, help_text='located below the products name', null=True, verbose_name='products short description ')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.SmallIntegerField()),
                ('available_amount', models.PositiveSmallIntegerField(verbose_name='available amount')),
                ('images', models.ImageField(upload_to='product_images')),
                ('short_point_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='short point 1')),
                ('short_point_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='short point 2')),
                ('short_point_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='short point 3')),
                ('short_point_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='short point 4')),
                ('information', models.TextField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='added date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='Product.category')),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Review_text', models.TextField()),
                ('spread_date', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Product.productmodel')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('spread_date',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='Product.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='Product.productmodel')),
            ],
        ),
    ]
