# Generated by Django 5.0.3 on 2024-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_productmodel_favorites_alter_productmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ManyToManyField(related_name='color', to='Product.productmodel'),
        ),
    ]
