# Generated by Django 5.0.3 on 2024-04-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_color_product_remove_color_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductEAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_EAV', to='Product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_EAV', to='Product.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_EAV', to='Product.size')),
            ],
            options={
                'verbose_name': 'product color and size',
                'ordering': ['-quantity'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductImages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.productmodel')),
            ],
        ),
    ]
