# Generated by Django 5.0.3 on 2024-04-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_productmodel_color_remove_productmodel_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sell_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Sell mount'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='favorites',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.PositiveSmallIntegerField(help_text='in percentage %', verbose_name='discount in percentage')),
                ('limit', models.PositiveSmallIntegerField(blank=True, help_text='Code Limitation', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Discount', to='Product.productmodel')),
            ],
        ),
    ]
