# Generated by Django 5.0.3 on 2024-05-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_productmodel_sell_count_alter_productmodel_favorites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTitleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banner_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_title', to='Product.productmodel')),
            ],
        ),
    ]
