# Generated by Django 5.0.3 on 2024-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_category_parent_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(related_name='products', to='Product.color'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(related_name='products', to='Product.size'),
        ),
    ]
