# Generated by Django 5.0.3 on 2024-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_remove_discountprice_product_discountprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountprice',
            name='product',
            field=models.ManyToManyField(related_name='discount', to='Product.productmodel'),
        ),
    ]
