# Generated by Django 5.0.3 on 2024-06-29 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_discountprice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountprice',
            name='product',
        ),
        migrations.AddField(
            model_name='discountprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='Product.productmodel'),
        ),
    ]
