# Generated by Django 5.0.3 on 2024-06-30 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_discountprice_product_discountprice_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='favorites',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
