# Generated by Django 5.0.3 on 2024-07-03 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_productmodel_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('4802a063-2d31-467d-891b-d4f7f94447ef')),
        ),
    ]
