# Generated by Django 5.0.3 on 2024-07-03 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_productmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a78fcfa-d8e1-4593-a240-ef1815f2c4c6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
