# Generated by Django 5.0.3 on 2024-07-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_alter_productmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='/static/static/img/no_product_image.png', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.productmodel'),
        ),
    ]
