# Generated by Django 5.0.3 on 2024-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='Product.color'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='Product.size'),
        ),
    ]
