# Generated by Django 5.0.3 on 2024-07-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_alter_productmodel_color_alter_productmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='/static/static/img/no_product_image.png', upload_to='ProductImages'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.productmodel'),
        ),
    ]
