# Generated by Django 5.0.3 on 2024-07-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Far.inspiredpencil.com%2Fpictures-2023%2Fno-product-image-available&psig=AOvVaw2fpkzMWBpN-0sV3XMDtSNq&ust=1720262618598000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNCC3-bbj4cDFQAAAAAdAAAAABAJ', upload_to='ProductImages'),
        ),
    ]
