# Generated by Django 5.0.3 on 2024-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/category_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='on_first_page',
            field=models.BooleanField(default=False, help_text='be shown on first page category', verbose_name='main page categories'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/ProductImages'),
        ),
        migrations.AlterField(
            model_name='sitetitlebanner',
            name='image',
            field=models.ImageField(upload_to='img/banner_image'),
        ),
    ]
