# Generated by Django 5.0.3 on 2024-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_category_image_category_on_first_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountprice',
            name='product',
        ),
        migrations.AddField(
            model_name='discountprice',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='discount', to='Product.productmodel'),
        ),
    ]
