# Generated by Django 5.0.3 on 2024-07-13 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_remove_discountprice_product_discountprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountprice',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='limitation', null=True),
        ),
        migrations.RemoveField(
            model_name='discountprice',
            name='product',
        ),
        migrations.AddField(
            model_name='discountprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='Product.productmodel'),
        ),
    ]
