# Generated by Django 5.0.3 on 2024-07-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_alter_discountprice_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountprice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='discountprice',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='discountprice',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='discountprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='discountprice',
            name='updated',
        ),
    ]
