# Generated by Django 5.0.3 on 2024-07-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_remove_discountprice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='in percentage %', verbose_name='discount in percentage'),
        ),
        migrations.AddField(
            model_name='discountprice',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='limitation', null=True),
        ),
        migrations.AddField(
            model_name='discountprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='Product.productmodel'),
        ),
    ]
