# Generated by Django 5.0.3 on 2024-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_discountprice_discount_rate_discountprice_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.RemoveField(
            model_name='discountprice',
            name='product',
        ),
        migrations.AddField(
            model_name='discountprice',
            name='product',
            field=models.ManyToManyField(related_name='discount', to='Product.productmodel'),
        ),
    ]
