# Generated by Django 5.0.3 on 2024-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_discountprice_is_active_remove_discountprice_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='event name'),
        ),
    ]
