# Generated by Django 5.0.3 on 2024-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_discountprice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='apply_to_all_products',
            field=models.BooleanField(default=False, verbose_name='Apply discount for all products'),
        ),
    ]
