# Generated by Django 5.0.3 on 2024-07-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_discountprice_apply_to_all_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountprice',
            name='apply_to_all_products',
            field=models.BooleanField(default=False, unique=True, verbose_name='Apply discount for all products'),
        ),
    ]
