# Generated by Django 5.0.3 on 2024-07-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_alter_discountprice_apply_to_all_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='Product.productcomment'),
        ),
    ]
