# Generated by Django 5.0.3 on 2024-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0036_productcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='spread_date',
            field=models.DateField(auto_now=True),
        ),
    ]
