# Generated by Django 5.0.3 on 2024-07-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0038_remove_productcomment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='favorites',
        ),
    ]
