# Generated by Django 5.0.3 on 2024-07-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_alter_productcomment_spread_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-spread_date',), 'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.RenameField(
            model_name='productcomment',
            old_name='Product',
            new_name='product',
        ),
    ]
