# Generated by Django 5.0.3 on 2024-07-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0048_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTitleBannerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='Product.productmodel')),
                ('sub_banner_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner1', to='Product.productmodel')),
                ('sub_banner_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner2', to='Product.productmodel')),
            ],
        ),
    ]
