# Generated by Django 5.0.3 on 2024-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0049_sitetitlebannerr'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SiteTitleBannerr',
        ),
    ]
