# Generated by Django 5.0.3 on 2024-07-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0050_productmodel_views_delete_sitetitlebannerr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='views',
        ),
    ]
