# Generated by Django 5.0.3 on 2024-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0053_alter_productmodel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
