# Generated by Django 5.0.3 on 2024-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0054_alter_color_title_alter_size_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
