# Generated by Django 5.0.3 on 2024-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0055_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='sub_products', to='Product.category'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='Product.color'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='Product.size'),
        ),
    ]
