# Generated by Django 5.0.3 on 2024-04-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('insta_account', models.CharField(max_length=100)),
                ('linkin_account', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('x_account', models.CharField(max_length=100)),
            ],
        ),
    ]
