# Generated by Django 5.0.3 on 2024-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_aboutus_model_a_1_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus_model',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
