# Generated by Django 5.0.3 on 2024-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_aboutus_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus_model',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
