# Generated by Django 5.0.3 on 2024-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_aboutus_model_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus_model',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
