# Generated by Django 5.0.3 on 2024-08-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_faqs_model_alter_aboutus_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='facebook',
            field=models.CharField(blank=True, help_text='your website facebook account', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='insta_account',
            field=models.CharField(blank=True, help_text='your website insta account', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='linkin_account',
            field=models.CharField(blank=True, help_text='your website linkin account', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='x_account',
            field=models.CharField(blank=True, help_text='your website x account', max_length=100),
        ),
    ]
