# Generated by Django 5.0.3 on 2024-08-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_sitecontact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
