# Generated by Django 5.0.3 on 2024-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_sitecontact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='twitter_account',
            field=models.URLField(blank=True, max_length=255, verbose_name='Tweeter URL'),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='insta_account',
            field=models.URLField(blank=True, max_length=255, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='linkin_account',
            field=models.URLField(blank=True, max_length=255, verbose_name='Linkin URL'),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='x_account',
            field=models.URLField(blank=True, max_length=255, verbose_name='X URL'),
        ),
    ]
