# Generated by Django 5.0.3 on 2024-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_sitecontact_twitter_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='site_description',
            field=models.TextField(null=True),
        ),
    ]
