# Generated by Django 5.0.3 on 2024-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='site_name',
            field=models.CharField(default='Multy Shop', max_length=50),
        ),
    ]
