# Generated by Django 5.0.3 on 2024-08-26 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Product', '0056_alter_productmodel_category_alter_productmodel_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': 'ordered product', 'verbose_name_plural': 'ordered products'},
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='will be filled automatically if not entered ', max_length=100, null=True, unique=True)),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='discount percentage')),
                ('discount_mount', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='decrement amount')),
                ('apply_to_total_price', models.BooleanField(default=False, verbose_name='apply discount to total price')),
                ('limitation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='Product.productmodel')),
                ('used_by', models.ManyToManyField(blank=True, editable=False, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
