# Generated by Django 5.0.3 on 2024-08-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_coupon_limitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='apply_to_total_price',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limitation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
